config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :leagues
  resources :sports
  resources :players
  resources :player_teams
  get '/home', to: 'sessions#new', as: 'home'
  post '/home', to: 'sessions#create', as: 'new_session'
  resources :sessions, only: [:new, :create]
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :sport
  has_many :teams, dependent: :destroy
  has_many :players, through: :teams
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :player_teams, dependent: :destroy
  has_many :teams, through: :player_teams
  has_many :leagues, through: :teams
  has_many :sports, through: :leagues
  has_secure_password

  validates :username, uniqueness: true
  validate :username_must_be_normal_characters

  def username_must_be_normal_characters
    if username.match(/[^a-zA-Z0-9]/)
      errors.add(:username, "must be alphanumeric characters")
    end
  end

  def name
    self.first_name + " " + self.last_name
  end


end

app/models/player_team.rb
class PlayerTeam < ApplicationRecord
  belongs_to :player
  belongs_to :team
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :leagues, dependent: :destroy
  has_many :teams, through: :leagues
  has_many :players, through: :teams
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :player_teams, dependent: :destroy
  has_many :players, through: :player_teams
  belongs_to :league

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized?

  private

  def log_in_player(player_id)
    session[:player_id] = player_id
  end

  def logged_in_player_id
    session[:player_id]
  end

  def get_logged_in_player
    @logged_in_player = Player.find(logged_in_player_id) if logged_in_player_id
  end

  def authorized?
    # if we do not have a valid user_id stored in cookie, kick us back over to login
    redirect_to new_session_path unless !!get_logged_in_player
  end

  def player_captain
    get_logged_in_player.captain == true
  end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  before_action :fetch_leagues, only: [:show, :edit, :update, :destroy]

  def index
    @leagues = League.all
  end

  def show
  end

  def new
    @league = League.new
    @sport
  end

  def create
    @league = League.new(league_params)
    if @league.save && @logged_in_player.admin
      redirect_to league_path(@league)
    else
      render :new
    end

  end

  def edit
  end

  def update
    @league.update[league_params(:league_name)]
    redirect_to @league
  end

  def destroy
    @league.destroy
    redirect_to leagues_path
  end

  private

  def fetch_leagues
    @league = League.find(params[:id])
  end

  def league_params
    params.require(:league).permit(:league_name, :sport_id)
  end

end

app/controllers/player_teams_controller.rb
class PlayerTeamsController < ApplicationController

  def new
    @teams = Team.all
    @player = Player.all
    @player_team = PlayerTeam.new
  end

  def create
    byebug
    @player_team = PlayerTeam.new(player_team_params)
    if @player_team.save
      redirect_to team_path(@player_team.team_id)
    else
      render :new
    end
  end

  private


  def player_team_params
    params.require(:player_team).permit(:player_id, :team_id)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authorized?, only: [:new, :create]
  before_action :fetch_player, only: [:show, :destroy, :edit, :update]

  def index
  end

  def show
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      log_in_player(@player.id)
      redirect_to player_path(@player), notice: "Player was succesfully registered"
    else
      # flash this below error
      flash[:errors] = @player.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    if @logged_in_player == @player
      @player.destroy
      redirect_to home_path
    end
  end

  private

  def player_params
    params.require(:player).permit(:username, :password, :password_digest, :first_name, :last_name, :captain, :admin)
  end

  def fetch_player
    @player = Player.find(params[:id])
  end

  def all_players
    @players = Player.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

skip_before_action :authorized?, only: %i[new create]

def new
  # code
end

def create
  @player = Player.find_by(username: session_params[:username])
  if @player && @player.authenticate(session_params[:password])
    log_in_player(@player.id)
    redirect_to player_path(@player)
  else
    @error = "Those credentials don't match anything we have in the database"
    render :new
  end
end

def destroy
  session.delete(:player_id)
  redirect_to new_session_path
end

private

def session_params
  params.require(:session).permit(:username, :password)
end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
before_action :set_sport, only: [:show, :edit, :update, :destroy]
before_action :select_leagues, only: :show
  def index
    @sports = Sport.all
  end

  def show

  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def get_leagues
    @leagues = League.all
  end

  def select_leagues
    @selected_leagues = get_leagues.select {|league| league.sport == @sport}
  end

  def sports_params
    params.require(:sport).permit(:sports_name)
  end

  def set_sport
    @sport = Sport.find(params[:id])
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :all_teams, only: :index
  def index
  end

  def show
  end

  def new
    @team = Team.new
  end

  def create
    if player_captain
      @team = Team.new(team_params)
      if @team.save
        redirect_to team_path
      else
        render :new
      end
    else

    end
  end

  def edit
  end

  def update
  end

  def destroy
    @team.destroy
  end

  private

  def team_params
    params.require(:team).permit(:team_name, :league_id)
  end

  def set_team
    @team = Team.find(params[:id])
  end

  def all_teams
    @teams = Team.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> RecLeagues </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <!-- <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "RecLeague", '/home', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if @logged_in_player %>
            <li class="logged_in_as_text"> Logged in as: <%= @logged_in_player.name %> </li>
            <li><%= link_to "My Profile", @logged_in_player %></li>
              <li><%= link_to "Log out", logout_path, method: 'delete' %></li>
            <% else %>
              <li><%= link_to "Register", new_player_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header> -->


<div class="ui inverted menu">
  <div class="header item">RecLeagues</div>
  <div class="item"> <%= link_to "My Profile", @logged_in_player %> </div>
  <div class="right menu">
    <% if @logged_in_player %>
      <p class="item" style="margin-bottom: 0px;"> Logged in as: <%= @logged_in_player.name %> </p>
      <p class="item"> <%= link_to "Log out", logout_path, method: 'delete' %> </p>
    <% else %>
    <p class="item"><%= link_to "Register", new_player_path %></li>
    <% end %>
  </div>
</div>

  <body>
    <div class ="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/leagues/new.html.erb
<h2>Create a new league</h2>

<%= form_with model: @league do |f| %>
  <%= f.label :league_name %>
  <%= f.text_field :league_name %>

  <%= f.label "Select Sport:" %>
  <%= f.collection_select :sport_id, Sport.all, :id, :sports_name %> <br>
  <%= f.submit %>
<% end %>

app/views/leagues/show.html.erb
<h1> <%= @league.league_name %> League Page </h1>

<% if @league.teams.empty? %>
  <%= "There are currently no teams in this league." %> <br>
    <% if @logged_in_player.captain %>
      <%= "As a League Captain, you may create your own." %>
    <% else %>
      <%= "Contact a League Captain to set up a team." %>
    <% end %>
<% else %>
  List of all teams in this league:
  <br>
  <% @league.teams.each do |team| %>
    <%= link_to team.team_name, team_path(team)  %> <br>
  <% end %>
<% end %>

<hr>
<% if @logged_in_player.captain %>
  <%= link_to "Create a new team", new_team_path %> <br>
<% end %>
<%= link_to "Return to view all leagues for #{@league.sport.sports_name}", sport_path(@league.sport) %>

app/views/player_teams/edit.html.erb
<h1> Manage Teams </h1>

<%= @ %>

  <%= form_with model: @player_team do |f| %>
    <%= f.label "Team Name:" %><br>
    <%= f.collection_select(:team_id, @teams, :id, :team_name) %>
    <%= f.hidden_field :player_id, value: @logged_in_player.id %>
    <%= f.submit "Join team" %>
  <% end %>

app/views/player_teams/new.html.erb
<h1> Join a team</h1>

<%= form_with model: @player_team do |f| %>
  <%= f.label "Team Name:" %><br>
  <%= f.collection_select(:team_id, @teams, :id, :team_name) %>
  <%= f.hidden_field :player_id, value: @logged_in_player.id %>
  <%= f.submit %>
  <% end %>


  <!-- ERROR MESSAGE -->
  <!-- (byebug) params
<ActionController::Parameters {"utf8"=>"✓", "authenticity_token"=>"dLymLBvZ1hjDp3yU7mi3BnancUAXh/dDgpfXwfrz3lB6AyjNNySWXh+WLi1eTYaVkypRJYXbxX02YYwfCj/HAw==", "player_team"=>"1", "commit"=>"Save ", "controller"=>"player_teams", "action"=>"create", "player_id"=>"1"} permitted: false>  -->

app/views/players/_form.html.erb
<%= form_with model: @player do |f| %>

<div class="error_explanation">
  <% if flash[:errors] %>
    <ol> <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
      <% end %></ol>
  <% end  %>
</div>


<p>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %> <br>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %> <br>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %> <br>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %> <br>
  </div>

  <div class="field">
      <%= f.label :captain %>
      <%= f.check_box :captain %> <br>
  </div>
  <br>
    <%= f.submit %>


<% end %>

app/views/players/edit.html.erb
<h2>Edit Player Profile</h2>

 <%= render partial: 'form' %>

app/views/players/new.html.erb
<h2>Register a new player</h2>

<h4>Please enter your information below to sign up for RecLeagues:</h4>

 <%= render partial: 'form' %>
<hr>
 <%= link_to "Return to Login", new_session_path %>

app/views/players/show.html.erb
<h1> <%= @player.name %> </h1>


<h2> Teams </h2>
  <% if @player.teams.empty? && @player == @logged_in_player %>
    <p> <%= @player.name %> is not part of any teams. Please click on the button below to join a team.
  <% else %>
    <% @player.teams.each do |team| %>
      <%= link_to team.team_name, team %><br>
    <% end %>

  <% end %> <br> <br> <br>
  <hr>

<% if @player == @logged_in_player %>
  <%= link_to "Join an existing team", new_player_team_path %> <br>
  <%= link_to "Leave a team", new_player_team_path %> <br>
  <%= link_to "Delete this player", player_path(@player), method: 'delete' %> <br>
  <% if @player.captain? %>
    <%= link_to "Create a team", new_team_path %><br>
  <% end %>
    <%= link_to "Browse available sports and leagues", sports_path %>
<% end %>

app/views/sports/index.html.erb
<h1>Current Sports Being Played at The League</h1>

<% @sports.each do |sport| %>
<%= link_to sport.sports_name, sport %> <br>
<% end %>

app/views/sports/show.html.erb
<h1> <%= @sport.sports_name %> </h1>


<% if @sport.leagues.empty? %>
  <%= "There are currently no leagues for this sport. Please contact an administrator to set up a league." %>
<% else %>
  <h3> Active leagues for <%= @sport.sports_name %> </h3>

  <% @selected_leagues.each do |league| %>

  <%= link_to league.league_name, league_path(league) %> <br>

  <% end %>
<% end %>

<hr>
<% if @logged_in_player.admin %>
<%= link_to "create a new league", new_league_path %><br>
<% else %>
<% end %>
<%= link_to "Return to view all sports", sports_path %>